spring.application.name=TokenGenerator
server.port=3002
server.servlet.context-path=/token-generator

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/token_generator?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
